### ISSUE TITLE
consider switching to FrontC package instead of vendoring

### ISSUE THREAD

**Issue by ivg** [goblint/cil#83]
We maintain the [FrontC][2]  ([opam package][1]) that stems from the original Hugues Cassé work.  We also work on adding more C99 and above features to the parser. In addition, we switched to menhir and added tons of tests.  I recently found this project and thought that it could be a good idea to unite our efforts. Ideally, CIL should be using FrontC as an opam dependency so that we can split parser and fronted and update them independently but other options are also on the table. 

So, are interested in this? 

[1]: https://opam.ocaml.org/packages/FrontC/
[2]: https://github.com/BinaryAnalysisPlatform/FrontC

**Comment by sim642** [comment]
Thanks for reaching out! It definitely sounds like a reasonable idea.

AFAIK FrontC was vendored into CIL over 20 years ago, well before we forked it and here a "complete rewrite" is claimed:
https://github.com/goblint/cil/blob/c47bbbdb442b4d50dac5a0879404ab3b5592170a/src/frontc/cparser.mly#L38-L41
I suppose one has to look into exactly how far from the original it deviated then and how far we have taken it since. So it might take an extensive amount of work to get things to common ground.



Also, Frama-C has vendored CIL, which in turn has vendored FrontC, and I think they have also made extensive updates (a bit of which we also recently extracted, #77), so there could be common ground there as well. Although I suspect their vendoring is even deeper and thus possibly unsuitable for extracting back to standalone FrontC.

**Comment by michael-schwarz** [comment]
Closing this as we are not actively pursuing this switch at the moment. We are however keeping an eye on the FrontC you guys maintain as well as the (re-surfaced) one by Hugues in case we find bugs in ours to see if there are fixes we can incorportae, and would invite you to do the same :blush:
